services:
  Netgen\IbexaImportExport\Core\FieldHandler\EzTags:
    parent: ez_migration_bundle.complex_field
    arguments:
      - '@ez_migration_bundle.tag_matcher'
      - "@translator"
    tags:
      - { name: ez_migration_bundle.complex_field, fieldtype: eztags, priority: 0 }

  Netgen\IbexaImportExport\Core\FieldHandler\EzRelation:
    parent: ez_migration_bundle.complex_field
    arguments:
      - "@ibexa.api.service.content"
      - "@translator"
    tags:
      - { name: ez_migration_bundle.complex_field, fieldtype: ezobjectrelation, priority: 0 }

  Netgen\IbexaImportExport\Core\FieldHandler\EzRelationList:
    parent: ez_migration_bundle.complex_field
    arguments:
      - "@ibexa.api.service.content"
      - "@translator"
    tags:
      - { name: ez_migration_bundle.complex_field, fieldtype: ezobjectrelationlist, priority: 0 }

  Netgen\IbexaImportExport\Core\FieldHandler\EzBinaryFile:
    parent: ez_migration_bundle.complex_field
    arguments:
      - '%kernel.project_dir%'
      - '%netgen_ibexa_import_export.storage_path%'
      - "@translator"
      - "$io.root_dir$"
      - "@?ibexa.core.io.default_url_decorator"
      - "@?ibexa.field_type.ezbinaryfile.io_service"
    tags:
      - { name: ez_migration_bundle.complex_field, fieldtype: ezbinaryfile, priority: 0 }

  Netgen\IbexaImportExport\Core\FieldHandler\EzImage:
    parent: ez_migration_bundle.complex_field
    arguments:
      - '%kernel.project_dir%'
      - '%netgen_ibexa_import_export.storage_path%'
      - "@translator"
      - "$io.root_dir$"
      - "@?ibexa.core.io.default_url_decorator"
      - '@ibexa.config.resolver'
    tags:
      - { name: ez_migration_bundle.complex_field, fieldtype: ezimage, priority: 0 }

  Netgen\IbexaImportExport\Core\FieldHandler\EzRichText:
    parent: ez_migration_bundle.complex_field
    arguments:
      - "@ibexa.api.service.content"
      - "@ibexa.api.service.location"
      - "@translator"
      - '@ez_migration_bundle.reference_resolver.customreference'
    tags:
      - { name: ez_migration_bundle.complex_field, fieldtype: ezrichtext, priority: 0 }

  Netgen\IbexaImportExport\Core\FieldHandler\NgEnhancedLink:
    parent: ez_migration_bundle.complex_field
    arguments:
      - "@ibexa.api.service.content"
      - "@translator"
    tags:
      - { name: ez_migration_bundle.complex_field, fieldtype: ngenhancedlink, priority: 0 }
